# Generated by Django 5.0.7 on 2024-08-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_carmodel_brand_alter_carmodel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Hatch_back', 'Hatch Back'), ('Hybrid', 'Hybrid')], default='Hybrid', max_length=10),
            preserve_default=False,
        ),
    ]
