# Generated by Django 5.0.7 on 2024-08-04 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_carmodel_body_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelTable(
            name='carmodel',
            table=('cars',),
        ),
    ]
